name: Build, test, and deploy

on:
  push:
    branches: [
      # main
      deployment
    ]
  pull_request: 
    branches: [
      # main
      deployment
    ]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./eLikas_backend

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Set Up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.5

    - name: Copy .env
      run: cp .env.testing .env

    - name: Composer Test Build (API)
      run: composer install

    # name: Create database

    # name: Build database

    # name: Test PHPStan
    # run: ./vendor/bin/phpstan analyse

    # name: TestPHPUnit
    # run: ./vendor/bin/phpunit

  deploy: 
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Connect Tailscale
        uses: tailscale/github-action@v4
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: Deploy API
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: 22
          key: ${{ secrets.SSHKEY }}
          script: |
            # Add GitHub's public SSH key to known hosts 
            ssh-keyscan -t ed25519 github.com >> ~/.ssh/known_hosts 2>/dev/null

            # Navigate to repository directory
            cd /var/www/elikas-capstone

            # Securely overwrite tracking files with the latest deployment branch
            git fetch origin
            git reset --hard origin/deployment

            # Target the script inside the subfolder, make it executable, and run it
            chmod +x /var/www/eLikas_backend/.scripts/deploy.sh
            bash < /var/www/eLikas_backend/.scripts/deploy.sh

      - name: Deploy Frontend eLikas app
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.FRONTEND_HOST }}
          username: ${{ secrets.FRONTEND_USERNAME }}
          port: 22
          key: ${{ secrets.FRONTEND_SSHKEY }}
          script: |
            # Add GitHub's public SSH key to known hosts
            ssh-keyscan -t ed25519 github.com >> ~/.ssh/known_hosts 2>/dev/null

            # Navigate to repository directory
            cd /var/www/elikas-capstone

            # Securely overwrite tracking files with the latest deployment branch
            git fetch origin
            git reset --hard origin/deployment
            
            # Target the script inside the subfolder, make it executable, and run it
            chmod +x /var/www/elikas-frontend/.scripts/deploy.sh
            bash < /var/www/elikas-frontend/.scripts/deploy.sh